package org.grajagan;

/**
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Tue Feb 28 18:28:15 PST 2012]
 *
 *  You should add additional methods to this class to meet the
 *  application requirements.  This class will only be generated as
 *  long as it does not already exist in the output directory.
 */
public class Tbl2Peer
    extends org.grajagan.BaseTbl2Peer
{
    /** Serial version */
    private static final long serialVersionUID = 1330482495970L;

}
